### ISSUE TITLE
Hydration attribute mismatch, when using the Modal in Nuxt 3

### ISSUE THREAD

**Issue by asrori7** [vexip-ui/vexip-ui#465] opened 2024-03-04 05:17 UTC
### Describe the bug

In the nuxt framework, using the modal, a Hydration attribute mismatch warning, will be prompted in the console.
![image](https://github.com/vexip-ui/vexip-ui/assets/14250248/1526f377-2e10-41f4-ad7f-75f577df9b92)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-uewfwc?file=app.vue

### Steps to reproduce

```
<script setup lang="ts">
const active = ref(false);
</script>

<template>
  <div>
    <VButton type="primary" @click="active = !active"> Open </VButton>

    <VModal
      v-model:active="active"
      transfer
      title="Title"
      :width="500"
      :height="300"
      modal-class="demo-modal"
    >
      <VNativeScroll use-y-bar height="100%" scroll-style="padding: 14px;">
        <p v-for="n in 20" :key="n">Some content</p>
      </VNativeScroll>
    </VModal>
  </div>
</template>

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment] 2024-03-05 12:54
duplicate of #463.

**Closed by qmhc** 2024-03-05 12:54 UTC
Labels: duplicate

**Comment by asrori7** [comment] 2024-03-06 02:53
of sorry, i don't know if the modal module is the same as the drawer
